# Generated by Django 3.2.18 on 2023-04-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaintainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='priority',
            field=models.IntegerField(db_column='priority', default=1),
        ),
    ]
