# Generated by Django 3.2.18 on 2023-05-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaintainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klineallsymbol',
            name='rsma',
            field=models.DecimalField(db_column='rsma', decimal_places=16, default=None, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='klineallsymbol',
            name='rsma_200',
            field=models.DecimalField(db_column='rsma_200', decimal_places=16, default=None, max_digits=32, null=True),
        ),
    ]
