# Generated by Django 3.2.18 on 2023-04-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaintainer', '0002_alter_symbol_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klineallsymbol',
            name='quote_asset_volume',
            field=models.IntegerField(db_column='quote_asset_volume', default=None, null=True),
        ),
    ]
