# Generated by Django 3.2.18 on 2023-05-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaintainer', '0002_auto_20230504_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klineallsymbol',
            name='rsma_200',
            field=models.DecimalField(db_column='rsma_200', decimal_places=14, default=None, max_digits=32, null=True),
        ),
    ]
