# Generated by Django 3.2.18 on 2023-04-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaintainer', '0003_alter_klineallsymbol_quote_asset_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klineallsymbol',
            name='kline_all_id',
            field=models.AutoField(db_column='kline_all_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(db_column='user_id', primary_key=True, serialize=False),
        ),
    ]
