# Generated by Django 3.2.18 on 2023-05-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamaintainer', '0005_auto_20230503_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='price',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='priority',
        ),
    ]
