# Generated by Django 3.2.18 on 2023-05-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaintainer', '0006_auto_20230504_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='klineallsymbol',
            name='rsma_200',
            field=models.DecimalField(db_column='rsma_200', decimal_places=8, default=None, max_digits=10, null=True),
        ),
    ]
