# Generated by Django 3.2.18 on 2023-05-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamaintainer', '0007_klineallsymbol_rsma_200'),
    ]

    operations = [
        migrations.AddField(
            model_name='klineallsymbol',
            name='rsd',
            field=models.FloatField(db_column='rsd', default=None, null=True),
        ),
    ]
